"""Add image_filename to RTDEItem, make icon optional

Revision ID: 0c6fd5ed13f8
Revises: 20251215_brand
Create Date: 2025-12-16 00:52:29.074709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c6fd5ed13f8'
down_revision = '20251215_brand'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rtde_count_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rtde_sessions_expires'))
        batch_op.drop_index(batch_op.f('ix_rtde_sessions_user_status'))
        batch_op.create_index(batch_op.f('ix_rtde_count_sessions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_rtde_count_sessions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('rtde_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=100), nullable=True))
        batch_op.alter_column('icon',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_rtde_items_active_order'))
        batch_op.create_index(batch_op.f('ix_rtde_items_active'), ['active'], unique=False)

    with op.batch_alter_table('rtde_session_counts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rtde_counts_session'))
        batch_op.create_index(batch_op.f('ix_rtde_session_counts_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rtde_session_counts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rtde_session_counts_session_id'))
        batch_op.create_index(batch_op.f('ix_rtde_counts_session'), ['session_id'], unique=False)

    with op.batch_alter_table('rtde_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rtde_items_active'))
        batch_op.create_index(batch_op.f('ix_rtde_items_active_order'), ['active', 'display_order'], unique=False)
        batch_op.alter_column('icon',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.drop_column('image_filename')

    with op.batch_alter_table('rtde_count_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rtde_count_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_rtde_count_sessions_status'))
        batch_op.create_index(batch_op.f('ix_rtde_sessions_user_status'), ['user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_rtde_sessions_expires'), ['expires_at'], unique=False)

    # ### end Alembic commands ###
