"""Add soft delete fields to users table

Revision ID: 38f7e23d7ea7
Revises: 2025110801
Create Date: 2025-11-20 18:14:22.595696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38f7e23d7ea7'
down_revision = '2025110801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_name_suggestions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_suggestions_category_name'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        # Add is_deleted as nullable first with default value
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True, server_default='false'))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_by', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['deleted_by'], ['id'], ondelete='SET NULL')

    # Update all existing rows to have is_deleted=False
    op.execute("UPDATE users SET is_deleted = FALSE WHERE is_deleted IS NULL")

    # Now make is_deleted NOT NULL
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_deleted', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_is_deleted'))
        batch_op.drop_column('deleted_by')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('item_name_suggestions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_suggestions_category_name'), ['category', 'name'], unique=False)
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False)

    # ### end Alembic commands ###
