"""Add category field to items table

Revision ID: a2b4409b87d0
Revises: 95337b169892
Create Date: 2025-10-17 23:54:57.023633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2b4409b87d0'
down_revision = '95337b169892'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=False))
        batch_op.create_index(batch_op.f('ix_items_category'), ['category'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_category'))
        batch_op.drop_column('category')

    # ### end Alembic commands ###
